interfaces:
  spine1:
    loopback: "10.2.1.3"
    int_numbered:
      swp49:
        ip_and_mask: "10.1.1.2/30"
      swp50:
        ip_and_mask: "10.1.1.6/30"
      swp51:
        ip_and_mask: "10.1.1.50/30"
      swp52:
        ip_and_mask: "10.1.1.54/30"
  spine2:
    loopback: "10.2.1.4"
    int_numbered:
      swp49:
        ip_and_mask: "10.1.1.18/30"
      swp50:
        ip_and_mask: "10.1.1.22/30"
      swp51:
        ip_and_mask: "10.1.1.34/30"
      swp52:
        ip_and_mask: "10.1.1.38/30"
  leaf1:
    loopback: "10.2.1.1"
    int_numbered:
      swp1s0:
        ip_and_mask: "10.1.1.1/30"
      swp1s1:
        ip_and_mask: "10.1.1.5/30"
      swp1s2:
        ip_and_mask: "10.1.1.33/30"
      swp1s3:
        ip_and_mask: "10.1.1.37/30"
    bridges:
      br0:
        ip_and_mask: "10.4.1.1/25"
        members: ["swp32s0"]
      br1:
        ip_and_mask: "10.4.1.129/25"
        members: ["swp32s1"]
  leaf2:
    loopback: "10.2.1.2"
    int_numbered:
      swp1s0:
        ip_and_mask: "10.1.1.17/30"
      swp1s1:
        ip_and_mask: "10.1.1.21/30"
      swp1s2:
        ip_and_mask: "10.1.1.49/30"
      swp1s3:
        ip_and_mask: "10.1.1.53/30"
    bridges:
      br0:
        ip_and_mask: "10.4.2.1/25"
        members: ["swp32s0"]
      br1:
        ip_and_mask: "10.4.2.129/25"
        members: ["swp32s1"]

hostnetranges:
  - 10.4.0.0/16

bgp:
  spine1:
    myasn: 65000
    peergroupv4:
      leafs:
        peerasn: 65000
        peers: ["10.1.1.1","10.1.1.5","10.1.1.49","10.1.1.53"]
        routereflectorclient: True
  spine2:
    myasn: 65000
    peergroupv4:
      leafs:
        peerasn: 65000
        peers: ["10.1.1.17","10.1.1.21","10.1.1.33","10.1.1.37"]
        routereflectorclient: True
  leaf1:
    myasn: 65000
    peergroupv4:
      spines:
        peerasn: 65000
        peers: ["10.1.1.2","10.1.1.6","10.1.1.34","10.1.1.38"]
  leaf2:
    myasn: 65000
    peergroupv4:
      spines:
        peerasn: 65000
        peers: ["10.1.1.18","10.1.1.22","10.1.1.50","10.1.1.54"]
